name: DOC Hut Scraper

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run scraper
      env:
        WEBHOOK_URL: https://hooks.zapier.com/hooks/catch/27048269/ung6i0f/
        WEBHOOK_URL_2: https://hooks.zapier.com/hooks/catch/27048269/unghe0s/
      run: node scraper.js
